name: Sync Wiki

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Sync Wiki
        run: ./.github/scripts/sync-wiki.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
